/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedImoveisRouteImport } from './routes/_authenticated/imoveis'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads.index'
import { Route as AuthenticatedCanvasIndexRouteImport } from './routes/_authenticated/canvas.index'
import { Route as AuthenticatedCanvasLeadIdRouteImport } from './routes/_authenticated/canvas.$leadId'
import { Route as AuthenticatedLeadsLeadIdJornadaRouteImport } from './routes/_authenticated/leads.$leadId.jornada'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedImoveisRoute = AuthenticatedImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCanvasIndexRoute =
  AuthenticatedCanvasIndexRouteImport.update({
    id: '/canvas/',
    path: '/canvas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCanvasLeadIdRoute =
  AuthenticatedCanvasLeadIdRouteImport.update({
    id: '/canvas/$leadId',
    path: '/canvas/$leadId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeadsLeadIdJornadaRoute =
  AuthenticatedLeadsLeadIdJornadaRouteImport.update({
    id: '/leads/$leadId/jornada',
    path: '/leads/$leadId/jornada',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/imoveis': typeof AuthenticatedImoveisRoute
  '/canvas/$leadId': typeof AuthenticatedCanvasLeadIdRoute
  '/canvas/': typeof AuthenticatedCanvasIndexRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
  '/leads/$leadId/jornada': typeof AuthenticatedLeadsLeadIdJornadaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/imoveis': typeof AuthenticatedImoveisRoute
  '/canvas/$leadId': typeof AuthenticatedCanvasLeadIdRoute
  '/canvas': typeof AuthenticatedCanvasIndexRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
  '/leads/$leadId/jornada': typeof AuthenticatedLeadsLeadIdJornadaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/imoveis': typeof AuthenticatedImoveisRoute
  '/_authenticated/canvas/$leadId': typeof AuthenticatedCanvasLeadIdRoute
  '/_authenticated/canvas/': typeof AuthenticatedCanvasIndexRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
  '/_authenticated/leads/$leadId/jornada': typeof AuthenticatedLeadsLeadIdJornadaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/dashboard'
    | '/imoveis'
    | '/canvas/$leadId'
    | '/canvas/'
    | '/leads/'
    | '/leads/$leadId/jornada'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/dashboard'
    | '/imoveis'
    | '/canvas/$leadId'
    | '/canvas'
    | '/leads'
    | '/leads/$leadId/jornada'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/imoveis'
    | '/_authenticated/canvas/$leadId'
    | '/_authenticated/canvas/'
    | '/_authenticated/leads/'
    | '/_authenticated/leads/$leadId/jornada'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/imoveis': {
      id: '/_authenticated/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof AuthenticatedImoveisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/canvas/': {
      id: '/_authenticated/canvas/'
      path: '/canvas'
      fullPath: '/canvas/'
      preLoaderRoute: typeof AuthenticatedCanvasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/canvas/$leadId': {
      id: '/_authenticated/canvas/$leadId'
      path: '/canvas/$leadId'
      fullPath: '/canvas/$leadId'
      preLoaderRoute: typeof AuthenticatedCanvasLeadIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads/$leadId/jornada': {
      id: '/_authenticated/leads/$leadId/jornada'
      path: '/leads/$leadId/jornada'
      fullPath: '/leads/$leadId/jornada'
      preLoaderRoute: typeof AuthenticatedLeadsLeadIdJornadaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImoveisRoute: typeof AuthenticatedImoveisRoute
  AuthenticatedCanvasLeadIdRoute: typeof AuthenticatedCanvasLeadIdRoute
  AuthenticatedCanvasIndexRoute: typeof AuthenticatedCanvasIndexRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
  AuthenticatedLeadsLeadIdJornadaRoute: typeof AuthenticatedLeadsLeadIdJornadaRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImoveisRoute: AuthenticatedImoveisRoute,
  AuthenticatedCanvasLeadIdRoute: AuthenticatedCanvasLeadIdRoute,
  AuthenticatedCanvasIndexRoute: AuthenticatedCanvasIndexRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
  AuthenticatedLeadsLeadIdJornadaRoute: AuthenticatedLeadsLeadIdJornadaRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
